# Generated by Django 4.0.5 on 2022-07-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('key', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('override', models.BooleanField()),
            ],
        ),
    ]
