# Generated by Django 4.0.5 on 2022-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_node_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
