# Generated by Django 4.0.5 on 2022-07-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_node_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.CharField(default='8547', max_length=250),
        ),
    ]
